module.exports = {
  EOL: '\n',
  arch: () => {},
  constants: {},
  cpus: () => {},
  endianness: () => {},
  freemem: () => {},
  homedir: () => {},
  hostname: () => {},
  loadavg: () => {},
  networkInterfaces: () => {},
  platform: () => {},
  release: () => {},
  tmpdir: () => {},
  totalmen: () => {},
  type: () => {},
  uptime: () => {},
  userInfo: () => {},
}